tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - lonefy.vscode-JS-CSS-HTML-formatter@0.2.3:i8S7423XUWOGOigQhW/Zbg==
    - formulahendry.auto-close-tag@0.5.8:E3l7NRdQytF0+ykejfHKdQ==
    - Zignd.html-css-class-completion@1.19.0:Soyzg8syqQX3vm86CKnPtg==
    - ecmel.vscode-html-css@0.2.3:hh8R73s3n0g/eQ8EL9PatQ==
    - pranaygp.vscode-css-peek@4.0.0:ul9Nm36TsnhjI3wWfCismA==
    - solnurkarim.html-to-css-autocompletion@1.1.2:kq1FmMkg+5u8Vjsk9lWcZA==
    - anseki.vscode-color@0.4.5:6L3EhKJFHuizA7wqZz6/+g==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - PKief.material-icon-theme@4.3.0:URe4ANXBLYHzB6CeGyTN8A==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - dracula-theme.theme-dracula@2.22.1:acEEGtphPo3sp9+wXQiSyw==
    - CoenraadS.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==